# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HTML5 Overview
email: dret@ca.com
description: > # this means to ignore newlines until "baseurl:"
  Keep track of the evolving HTML5 landscape! New specifications and
  specification updates are tracked faithfully on this site.
baseurl: "/HTML5-overview" # the subpath of your site, e.g. /blog
url: "http://dret.github.io" # the base hostname & protocol for your site
twitter_username: dret
github_username:  dret

# Build settings
markdown: kramdown
